app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Non authenticated pages
use Phonex\Jobs\CreateUserWithSubscriber;
use Phonex\Jobs\IssueProductLicense;
use Phonex\Jobs\RefreshSubscribers;
use Phonex\Model\Product;
use Phonex\User;

Route::get('home', 'HomeController@index');
Route::get('/', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
    'trial' => 'AccountController',
    'account' => 'AccountController', //alias
]);

Route::get('login', 'Auth\AuthController@getLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

Route::resource('products', 'Api\ProductControllerLegacy', ['only' => ['show', 'index']]);
Route::controller('qa', 'QaController'); // qa tools
Route::get('api/support-notifications/batch', 'Api\SupportNotificationsController@getBatch');
Route::post('api/support-notifications/batch', 'Api\SupportNotificationsController@postBatch');
Route::get('api/support-notification/{user}/{notification}', 'Api\SupportNotificationsController@getNotificationForUser');

Route::any('api/version-check', 'Api\VersionCheckController@versionCheck');

// Authenticated API using client certs
Route::group(['prefix'=>'api/auth/', 'middleware'=>['auth.client_cert']], function(){
    Route::get('products/apple', 'Api\ProductController@getAppleProducts');
    Route::get('products/google', 'Api\ProductController@getGoogleProducts');

    Route::get('products/available', 'Api\ProductController@getAvailableProducts');
    Route::get('products/purchased', 'Api\ProductController@getPurchasedProducts');
    Route::get('products/list-from-licenses', 'Api\ProductController@getLicensesProducts'); // List arbitrary user's products by providing license ids
    Route::any('purchase/appstore/payment-verif', 'Api\PurchaseController@postApplePaymentVerification');
    Route::any('purchase/play/payment-verif', 'Api\PurchaseController@postAndroidPaymentVerification');
    Route::any('purchase/play/payments-verif', 'Api\PurchaseController@postAndroidPaymentsVerification');
});

// Authenticated pages using client credentials
Route::group(['middleware' => ['auth', 'acl']], function() {
    Route::get('/', 'HomeController@index');

    /* Users + details */
	Route::resource('users', 'UserController');
    Route::post('users/{user}/reset-trial-counter', ['as'=>'users.reset-trial-counter', 'uses'=>'UserController@resetTrialCounter']);
    Route::get('users/{user}/push-lic-update', ['as'=>'users.push-lic-update', 'uses'=>'UserController@pushLicUpdate']);
    Route::post('users/{user}/force-logout', ['as'=>'users.force-logout', 'uses'=>'UserController@forceLogout']);
    // CL
    Route::get('users/{user}/licenses', ['as' => 'users.licenses', 'uses' => 'UserController@showLicenses']);
    Route::get('users/{user}/cl', ['as' => 'users.cl', 'uses' => 'UserController@showCl']);
    Route::get('users/{user}/stats', ['as' => 'users.stats', 'uses' => 'UserController@showStats']);
    Route::get('users/{user}/reg-stats', ['as' => 'users.reg-stats', 'uses' => 'UserController@showRegStats']);
    Route::get('users/{user}/error-reports', ['as' => 'users.error-reports', 'uses' => 'UserController@showErrorReports']);

    // Contact lists + alternative via get
    Route::delete('users/{user}/cl', ['uses' => 'UserController@deleteContact']);
    Route::delete('users/{user}/cl/{contactUser}', ['uses' => 'UserController@deleteContact']);
    Route::get('users/{user}/cl/delete/{contactUser}', ['uses' => 'UserController@deleteContact']);

    Route::get('users/{users}/new-license', ['as' => 'users.new-license', 'uses' => 'UserController@getNewLicense']);
    Route::post('users/{users}/new-license', ['as' => 'users.new-license', 'uses' => 'UserController@postNewLicense']);
    Route::patch('users/{users}/change-password', ['as' => 'users.change_password', 'uses' => 'UserController@changePassword']);
    Route::patch('users/{users}/add-user-to-cl', ['as' => 'users.add_user_to_cl', 'uses' => 'UserController@addUserToCl']);

    /* Group */
    Route::resource('groups', 'GroupController');
    Route::get('groups/{user}/users', ['as' => 'groups.users', 'uses' => 'GroupController@showUsers']);
    Route::get('groups/{user}/bcodes', ['as' => 'groups.bcodes', 'uses' => 'GroupController@showCodes']);

    /* Licenses */
    Route::resource('licenses', 'LicenseController', ['only' => ['index', 'edit', 'update', 'destroy']]);
    Route::get('licenses/delete/{id}', ['as'=>'licenses.delete', 'uses' => 'LicenseController@destroy']);

    /* Business Codes */
    Route::controller('bcodes', 'BusinessCodeController');

    /* Statistics */
    Route::controller('stats', 'StatsController');

    /* Reports */
    Route::get('reports/last-errors', 'ReportsController@lastErrors');
    Route::get('reports/last-trial-requests', 'ReportsController@lastTrialRequests');
    Route::post('reports/reset-trial-counter', 'ReportsController@resetTrialCounter');

    /* Admin only pages */
    Route::get('logs', ['acl-resource' => 'logs',
        'uses' => '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index'
    ]);
    Route::any('adminer', ['acl-resource' => 'adminer',
        'uses' => '\Miroc\LaravelAdminer\AdminerController@index']);
});

app/LicenseType.php
<?php namespace Phonex;

use Illuminate\Database\Eloquent\Model;

/**
 * @property mixed days
 * @property mixed id
 */
class LicenseType extends Model{
    const EXPIRATION_DAY = "day";
    const EXPIRATION_WEEK = "week";
    const EXPIRATION_MONTH = "month";
    const EXPIRATION_QUARTER = "quarter";
    const EXPIRATION_HALF_YEAR = "half_year";
    const EXPIRATION_YEAR = "year";
    const EXPIRATION_INFINITE = "infinite";
    const EXPIRATION_CONSUMABLE = "consumable";

    protected $table = "license_types";
    
    public function licenses(){
        return $this->hasMany('Phonex\License', 'license_type_id');
    }

    /* Helpers */
    public function readableType(){
        return ucfirst($this->name) . " (" .  $this->days . " days )";
    }

    public static function getWeek(){
        return self::findByName(self::EXPIRATION_WEEK);
    }
    public static function getDay(){
        return self::findByName(self::EXPIRATION_DAY);
    }
    public static function getMonth(){
        return self::findByName(self::EXPIRATION_MONTH);
    }
    public static function getQuarterOfYear(){
        return self::findByName(self::EXPIRATION_QUARTER);
    }
    public static function getHalfYear(){
        return self::findByName(self::EXPIRATION_HALF_YEAR);
    }
    public static function getYear(){
        return self::findByName(self::EXPIRATION_YEAR);
    }
    public static function getInfinite(){
        return self::findByName(self::EXPIRATION_INFINITE);
    }

    public static function findByName($name){
        return LicenseType::where('name', $name)->first();
    }

    /* Accessors */
    //uc_name_with_days
    public function getUcNameWithDaysAttribute()
    {
        return ucfirst($this->name) . " (" . $this->days . " days)";
    }

    public function getUcNameAttribute()
    {
        return ucfirst($this->name);
    }


}

app/Subscriber.php
<?php namespace Phonex;
use Phonex\Model\AppVersion;
use Illuminate\Database\Eloquent\Model;
use Phonex\Exceptions\InvalidStateException;
use Phonex\Exceptions\SubscriberAlreadyInCLException;
use GeoIP;
use Phonex\Utils\SortableTrait;

/**
 * @property  username
 * @property mixed id
 * @property mixed email_address
 * @property string turnPasswd
 * @property  license_type
 */
class Subscriber extends Model{
    use SortableTrait;

    /* Definition */
    protected $connection = 'mysql_opensips';
    protected $table = 'subscriber';
    // attribute required by SortableTrait
    protected $sortable = ['date_last_activity', 'issued_on', 'expires_on'];

    // legacy - Subscriber table doesn't have timestamps
    public $timestamps = false;
    protected $dates = ['expires_on', 'issued_on',
        'date_last_activity',
        'date_first_login',
        'date_first_user_added',
        'date_first_authCheck',
        'date_last_activity',
        'date_last_authCheck',
        'date_last_pass_change'
    ];

    public function subscribersInContactList(){
        return $this
            ->belongsToMany('Phonex\Subscriber', 'contactlist', 'subscriber_id', 'int_usr_id')
            ->withPivot('displayName');
    }

    public function setPasswordFields($password){
        if (empty($this->username) || empty($this->domain)){
            throw new InvalidStateException('Cannot set password fields (HA1_1, HA1_2) because username or domain is empty in this object.');
        }

        $sip = $this->username . "@" . $this->domain;

        $ha1 = getHA1_1($sip, $password);
        $ha1b = getHA1_2($sip, $this->domain, $password);

        $this->ha1 = $ha1;
        $this->ha1b = $ha1b;
    }

    public function user(){
        return $this->hasOne('Phonex\User'); // looks for subscriber_id in User table
    }

    /* Accessors */
    // helper to resolve locale of subscriber - might be null if locale is not recorder
    public function getAppPriorityLocaleAttribute()
    {
        if (!$this->app_version_obj || !$this->app_version_obj->locales){
            // if we cannot figure locale, return null
            return null;
        }
        // locales are order by priority
        // locale can be in format "en_US", split string by '_' and take the first part
//        $locale = explode('_', $appVersionObj->locales[0])[0];
        $this->app_version_obj->locales[0];
    }

    // ->app_version_obj
    public function getAppVersionObjAttribute()
    {
        if ($this->app_version){
            return new AppVersion($this->app_version);
        } else {
            return null;
        }
    }

    public function getLocationAttribute()
    {
        if($this->last_action_ip){
            return GeoIP::getLocation($this->last_action_ip);
        } else {
            return null;
        }
    }

    public function getFormattedLocationAttribute()
    {
        if ($this->location){
            $s = "IP: " . $this->location['ip'] . "<br />" .
//                "ISO Code: " . $this->location['isoCode'] . "<br />" .
                "Country: " . $this->location['country'] . "<br />" .
                "City: " . $this->location['city'] . "<br />" .
                "State: " .$this->location['state'] . "<br />" .
//                "Postal code: " . $this->location['postal_code'] . "<br />" .
                "Latitude: " . $this->location['lat'] . "<br />" .
                "Longitude: " . $this->location['lon'] . "<br />" .
                "Timezone: " . $this->location['timezone'];
//                "Continent: " . $this->location['continent'] . "<br />";
            return $s;
        } else {
            return '';
        }
    }

    /* Helpers */
    public function deleteWithContactListRecords(){
        ContactList::where('subscriber_id', $this->id)
            ->orWhere('int_usr_id', $this->id)
            ->delete();

        SupportContact::where('owner_sip', $this->email_address)->delete();
        $this->delete();
    }

    public function addToContactList(Subscriber $subscriber, $displayName){
        $count = ContactList::whereRaw('subscriber_id=? and int_usr_id=?', [$this->id, $subscriber->id])->count();
        if ($count > 0){
            throw new SubscriberAlreadyInCLException($this, $subscriber);
        }
        // mutual attributes
        $record1 = new ContactList();
        $record1->entryState = "ENABLED";
        $record1->objType = "INTERNAL_USER";
        $record1->hideInContactList = 0;
        $record1->inBlacklist = 0;
        $record1->inWhitelist = 1;

        $record1->int_usr_id = $subscriber->id;
        $record1->subscriber_id = $this->id; // owner
        $record1->displayName = $displayName;

        return $record1->save();
    }

    public function removeFromContactList(Subscriber $subscriber){
        $this->subscribersInContactList()->detach($subscriber->id);
    }

    public static function newSubscriber($username, $password, $startsAt = null, $expiresAt = null, $licenseType = "none", $domain = 'phone-x.net'){
        return self::createSubscriber($username, $password, $startsAt, $expiresAt, $licenseType, $domain);
    }

    /**
     * @deprecated use newSubscriber, license start/end is now stored in usage_policy_current and usage_policy_expired
     */
    public static function createSubscriber($username, $password, $startsAt, $expiresAt, $licenseType, $domain = 'phone-x.net'){
        $sip = $username . "@" . $domain;
        $ha1 = getHA1_1($sip, $password);
        $ha1b = getHA1_2($sip, $domain, $password);

        $subscriber = new Subscriber();
        $subscriber->username = $username;
        $subscriber->domain = $domain;
//        $sipUser->password =
        $subscriber->email_address = $sip;

        $subscriber->license_type = $licenseType;

        $subscriber->ha1 = $ha1;
        $subscriber->ha1b = $ha1b;
        $subscriber->rpid = 0;
        $subscriber->isAdmin = 0;
        $subscriber->primaryGroup = 0;
        $subscriber->canSignNewCert = 1;
        $subscriber->forcePasswordChange = 1;
        $subscriber->issued_on = $startsAt;
        $subscriber->expires_on = $expiresAt;

        // LS-5 Initialize TURN password for new users.
        $subscriber->turnPasswd = getRandomString(24);
        // Pre-computed ha1 password for turn server
        $subscriber->turn_passwd_ha1b = getHA1_B($sip, $subscriber->turnPasswd);

        return $subscriber;
    }
}

resources/views/user/chips/cl-table.blade.php
{{--
Parameters: $user
--}}

@if($user->subscriber && count($user->subscriber->subscribersInContactList) > 0)
    <table class="table table-condensed">
        <tr>
            <th>Username</th>
            <th>Alias</th>
            <th>Options</th>
        </tr>
        @foreach($user->subscriber->subscribersInContactList as $subscriberContact)
            <tr>
                <td>
                    @if($subscriberContact->user)
                        <a href="{{ \URL::route('users.show', [ $subscriberContact->user->id ]) }}">{{ $subscriberContact->user->username }}</a>
                    @else
                        {{ $subscriberContact->username }} (corrupted! - missing record in License Server DB)
                    @endif
                </td>
                <td>{{ $subscriberContact->pivot->displayName }}</td>
                <td>
                    <div class="btn-group  btn-group-xs">
                        @if($subscriberContact->user)
                        <a type="button" class="btn btn-danger" href="#" title="Delete"
                           data-href="/users/{{$user->id}}/cl/delete/{{$subscriberContact->user->id}}" data-toggle="modal" data-target="#confirm-delete"><i class="fa fa-trash-o"></i> Delete</a>
                        @endif
                    </div>
                </td>
            </tr>
        @endforeach
    </table>
    <p>Total: {{ $user->subscriber->subscribersInContactList->count() }}</p>
@else
    Empty contact list
@endif

@include('dialogs.contact-delete')

<hr />

resources/views/user/chips/errors-table.blade.php
{{--
Parameters: $reports, $with_username
--}}
@if($reports)
    <table class="table table-condensed">
        <tr>
            <th>ID</th>
            <th>Date</th>
            @if($with_username)
                <th>Username</th>
            @endif
            <th>App info</th>
            <th>User message</th>
            <th>Filename</th>
        </tr>
        @foreach($reports as $report)
            <tr>
                <td>{{$report->id}}</td>
                <td>{{$report->date_created}}</td>
                @if($with_username)
                    <td>{{$report->userName}}</td>
                @endif
                <td>{{$report->appVersion}}</td>
                <td>{{$report->userMessage}}</td>
                <td>{{$report->filename}}</td>
            </tr>
        @endforeach
    </table>
    <p>Total: {{ $reports->count() }}</p>
@else
    No error reports
@endif

resources/views/user/chips/form-new-license.blade.php
<div class="form-group">
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                <label for="starts_at" class="control-label">Start date*</label>
                <div class="input-group date">
                    <input value="{{ old('starts_at') }}" type="text" name="starts_at" class="form-control" />
                    <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            $(function () {
                $('#starts_at').daterangepicker();
            });
        </script>

        <div class="col-md-2">
            <label for="password" class="control-label">Product*</label>
            <select name="product_id" class="form-control">
                @foreach($products as $product)
                    <option value="{{ $product->id }}">{{ $product->uc_name . " (" . $product->platform . ")" }} </option>
                @endforeach
            </select>
        </div>

    </div>
</div>

<div class="row">
    <div class="col-md-4 ">
        <div class="form-group">
            <label for="password" class="control-label">License notes</label>
            <textarea name="comment" class="form-control" rows="3">{{ old('comment') }}</textarea>
        </div>
    </div>
</div>

resources/views/user/chips/top-nav.blade.php
<ul class="nav nav-tabs">
    <li role="presentation" @if(Route::is('users.show')) class="active" @endif ><a href="{{ route('users.show', [ $user->id ]) }}">Details</a></li>
    <li role="presentation" @if(Route::is('users.licenses')) class="active" @endif><a href="{{ route('users.licenses', [ $user->id ]) }}">Licenses</a></li>
    <li role="presentation" @if(Route::is('users.cl')) class="active" @endif><a href="{{ route('users.cl', [ $user->id ]) }}">Contact List</a></li>
    <li role="presentation" @if(Route::is('users.stats')) class="active" @endif><a href="{{ route('users.stats', [ $user->id ]) }}">Activity statistics</a></li>
    <li role="presentation" @if(Route::is('users.error-reports')) class="active" @endif><a href="{{ route('users.error-reports', [ $user->id ]) }}">Error reports</a></li>
    <li role="presentation" @if(Route::is('users.reg-stats')) class="active" @endif><a href="{{ route('users.reg-stats', [ $user->id ]) }}">Registration monitor</a></li>
</ul>

resources/views/user/chips/user-details.blade.php
{{--
Parameters: $user
--}}

<h4>User details</h4>

<div class="row">
    <div class="col-md-4 ">
        <dl>
            <dt>Username</dt>
            <dd>{{ $user->username }}</dd>
        </dl>
    </div>
    <div class="col-md-4 ">
        <dl>
            <dt>Email Address</dt>
            <dd>{{ $user->email or '-'}}</dd>
        </dl>
    </div>
</div>

<div class="row">
    <div class="col-md-4 ">
        <dl>
            <dt>Has access</dt>
            <dd>@if ($user->has_access) Yes @else No @endif</dd>
        </dl>
    </div>
    <div class="col-md-4 ">
        </dl>
            <dt>Date created</dt>
            <dd>{{ date_simple($user->dateCreated) }}</dd>
        </dl>
    </div>
    <div class="col-md-4 ">
        <dl>
            <dt>Date updated</dt>
            <dd>{{ date_simple($user->dateUpdated) }}</dd>
        </dl>
    </div>
</div>

<div class="row">
    <div class="col-md-4 ">
        </dl>
            <dt>Current user policy</dt>
            <dd>@if($user->subscriber) {{ $user->subscriber->usage_policy_current }} @else - @endif</dd>
        </dl>
    </div>
</div>



@if($user->comment)
    <div class="row">
        <div class="col-md-4 ">
            </dl>
                <dt>Comment</dt>
                <dd>{{ $user->comment }}</dd>
            </dl>
        </div>
    </div>
@endif

<h4>Login details</h4>

@if($user->subscriber)
<div class="row">
    @if($user->subscriber->location)
        <div class="col-md-4 ">
            <dl>
            <dt>Location</dt>
            <dd>{!! $user->subscriber->formatted_location !!}</dd>
            </dl>
        </div>
    @endif
    @if($user->subscriber->app_version)
    <div class="col-md-4 ">
        </dl>
        <dt>Phone</dt>
        <dd>{{ $user->subscriber->app_version_obj->platformDesc() . " " . $user->subscriber->app_version_obj->device() }}</dd>
        </dl>
    </div>
    <div class="col-md-4 ">
        <dl>
            <dt>Application</dt>
            <dd>{{ $user->subscriber->app_version_obj->versionDesc() }}</dd>
        </dl>
    </div>
    @endif

</div>


    <div class="row">
        <div class="col-md-4 ">
            <dl>
                <dt>First authentication</dt>
                <dd>{{ $user->subscriber->date_first_authCheck or '-'}}</dd>
            </dl>
        </div>

        <div class="col-md-4 ">
            <dl>
                <dt>First cert generation</dt>
                <dd>{{ $user->subscriber->date_first_login or '-'}}</dd>
            </dl>
        </div>

        <div class="col-md-4 ">
            <dl>
                <dt>First user added</dt>
                <dd>{{ $user->subscriber->date_first_user_added or '-'}}</dd>
            </dl>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 ">
            <dl>
                <dt>Last activity</dt>
                <dd>{{ $user->subscriber->date_last_activity or '-'}}</dd>
            </dl>
        </div>

        <div class="col-md-4 ">
            <dl>
                <dt>Last authentication</dt>
                <dd>{{ $user->subscriber->date_last_authCheck or '-'}}</dd>
            </dl>
        </div>

        <div class="col-md-4 ">
            <dl>
                <dt>Last password changed</dt>
                <dd>{{ $user->subscriber->date_last_pass_change or '-'}}</dd>
            </dl>
        </div>
    </div>

    {{--Feature especially for Dusan--}}
    @if(strlen($user->subscriber->ha1)<32)
        <div class="alert alert-danger" role="alert">
            <span class="fa fa-exclamation-triangle" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            User has corrupted password! Workaround: reset password.
        </div>
    @endif

@else
    User has no SIP license issued yet, therefore no details are available
@endif

resources/views/user/chips/users-simple-table.blade.php
{{--
Parameters: $users
--}}

@if($users && $users->count() > 0)
    <table class="table table-condensed  table-striped">

        <thead>
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Created at</th>
            <th>Last activity</th>
            <th>Cur. lic. type</th>
            {{--<th>Cur. lic. starts</th>--}}
            <th>Cur. lic. expires</th>
            <th>Phone / Version</th>
            <th>Location</th>
            <th class="text-center">Options</th>
        </tr>
        </thead>

        <tbody>
        @foreach($users as $user)
            <tr>

                <td>{{ $user->id }}</td>
                <td>
                    <a href="{{ \URL::route('users.show', [ $user->id ]) }}">{{ $user->username }}</a>
                </td>
                <td>{{ $user->dateCreated }}</td>

                <td>@if($user->subscriber) {{ $user->subscriber->date_last_activity }} @endif</td>
                <td>@if($user->activeLicense) {{ $user->activeLicense->readable_type }} @endif</td>
{{--                <td>@if($user->subscriber) {{ $user->subscriber->issued_on }} @endif</td>--}}
                <td>@if($user->subscriber) {{ $user->subscriber->expires_on }} @endif</td>
                <td>
                    @if($user->subscriber && $user->subscriber->app_version)
                        {{$user->subscriber->app_version_obj->platformDesc() . " / " . $user->subscriber->app_version_obj->versionDesc()}}
                    @endif
                </td>
                <td>
                    @if($user->subscriber && $user->subscriber->location)
                        {{$user->subscriber->location['country']}}
                        @if($user->subscriber->location['city'])
                            {{ ", " . $user->subscriber->location['city'] }}
                        @endif
                    @endif
                </td>

                <td class="text-center">
                    <div class="btn-group  btn-group-xs">
                        <a class="btn btn-info view-btn-edit" href="{{ route('users.show', $user->id) }}" title="Details"><i class="fa fa-pencil-square-o"></i> Details</a>
                        <a class="btn btn-info view-btn-edit" href="{{ route('users.licenses', $user->id) }}" title="Licenses"><i class="fa fa-book"></i> Licenses</a>
                        <a class="btn btn-info view-btn-edit" href="{{ route('users.cl', $user->id) }}" title="Contact List"><i class="fa fa-list-alt"></i> Contact List</a>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <p>Total: {{ $users->count() }}</p>
@else
    No users
@endif