app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Non authenticated pages
use Phonex\Jobs\CreateUserWithSubscriber;
use Phonex\Jobs\IssueProductLicense;
use Phonex\Jobs\RefreshSubscribers;
use Phonex\Model\Product;
use Phonex\User;

Route::get('home', 'HomeController@index');
Route::get('/', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
    'trial' => 'AccountController',
    'account' => 'AccountController', //alias
]);

Route::get('login', 'Auth\AuthController@getLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

Route::resource('products', 'Api\ProductControllerLegacy', ['only' => ['show', 'index']]);
Route::controller('qa', 'QaController'); // qa tools
Route::get('api/support-notifications/batch', 'Api\SupportNotificationsController@getBatch');
Route::post('api/support-notifications/batch', 'Api\SupportNotificationsController@postBatch');
Route::get('api/support-notification/{user}/{notification}', 'Api\SupportNotificationsController@getNotificationForUser');

Route::any('api/version-check', 'Api\VersionCheckController@versionCheck');

// Authenticated API using client certs
Route::group(['prefix'=>'api/auth/', 'middleware'=>['auth.client_cert']], function(){
    Route::get('products/apple', 'Api\ProductController@getAppleProducts');
    Route::get('products/google', 'Api\ProductController@getGoogleProducts');

    Route::get('products/available', 'Api\ProductController@getAvailableProducts');
    Route::get('products/purchased', 'Api\ProductController@getPurchasedProducts');
    Route::get('products/list-from-licenses', 'Api\ProductController@getLicensesProducts'); // List arbitrary user's products by providing license ids
    Route::any('purchase/appstore/payment-verif', 'Api\PurchaseController@postApplePaymentVerification');
    Route::any('purchase/play/payment-verif', 'Api\PurchaseController@postAndroidPaymentVerification');
    Route::any('purchase/play/payments-verif', 'Api\PurchaseController@postAndroidPaymentsVerification');
});

// Authenticated pages using client credentials
Route::group(['middleware' => ['auth', 'acl']], function() {
    Route::get('/', 'HomeController@index');

    /* Users + details */
	Route::resource('users', 'UserController');
    Route::post('users/{user}/reset-trial-counter', ['as'=>'users.reset-trial-counter', 'uses'=>'UserController@resetTrialCounter']);
    Route::get('users/{user}/push-lic-update', ['as'=>'users.push-lic-update', 'uses'=>'UserController@pushLicUpdate']);
    Route::post('users/{user}/force-logout', ['as'=>'users.force-logout', 'uses'=>'UserController@forceLogout']);
    // CL
    Route::get('users/{user}/licenses', ['as' => 'users.licenses', 'uses' => 'UserController@showLicenses']);
    Route::get('users/{user}/cl', ['as' => 'users.cl', 'uses' => 'UserController@showCl']);
    Route::get('users/{user}/stats', ['as' => 'users.stats', 'uses' => 'UserController@showStats']);
    Route::get('users/{user}/reg-stats', ['as' => 'users.reg-stats', 'uses' => 'UserController@showRegStats']);
    Route::get('users/{user}/error-reports', ['as' => 'users.error-reports', 'uses' => 'UserController@showErrorReports']);

    // Contact lists + alternative via get
    Route::delete('users/{user}/cl', ['uses' => 'UserController@deleteContact']);
    Route::delete('users/{user}/cl/{contactUser}', ['uses' => 'UserController@deleteContact']);
    Route::get('users/{user}/cl/delete/{contactUser}', ['uses' => 'UserController@deleteContact']);

    Route::get('users/{users}/new-license', ['as' => 'users.new-license', 'uses' => 'UserController@getNewLicense']);
    Route::post('users/{users}/new-license', ['as' => 'users.new-license', 'uses' => 'UserController@postNewLicense']);
    Route::patch('users/{users}/change-password', ['as' => 'users.change_password', 'uses' => 'UserController@changePassword']);
    Route::patch('users/{users}/add-user-to-cl', ['as' => 'users.add_user_to_cl', 'uses' => 'UserController@addUserToCl']);

    /* Group */
    Route::resource('groups', 'GroupController');
    Route::get('groups/{user}/users', ['as' => 'groups.users', 'uses' => 'GroupController@showUsers']);
    Route::get('groups/{user}/bcodes', ['as' => 'groups.bcodes', 'uses' => 'GroupController@showCodes']);

    /* Licenses */
    Route::resource('licenses', 'LicenseController', ['only' => ['index', 'edit', 'update', 'destroy']]);
    Route::get('licenses/delete/{id}', ['as'=>'licenses.delete', 'uses' => 'LicenseController@destroy']);

    /* Business Codes */
    Route::controller('bcodes', 'BusinessCodeController');

    /* Statistics */
    Route::controller('stats', 'StatsController');

    /* Reports */
    Route::get('reports/last-errors', 'ReportsController@lastErrors');
    Route::get('reports/last-trial-requests', 'ReportsController@lastTrialRequests');
    Route::post('reports/reset-trial-counter', 'ReportsController@resetTrialCounter');

    /* Admin only pages */
    Route::get('logs', ['acl-resource' => 'logs',
        'uses' => '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index'
    ]);
    Route::any('adminer', ['acl-resource' => 'adminer',
        'uses' => '\Miroc\LaravelAdminer\AdminerController@index']);
});

app/Group.php
<?php namespace Phonex;

use Illuminate\Database\Eloquent\Model;

class Group extends Model{
	protected $table = 'groups';
    protected $fillable = ['name', 'owner_id'];

    public function users()
    {
        return $this->belongsToMany('Phonex\User', 'user_group', 'group_id', 'user_id');
    }

    public function owner()
    {
        return $this->belongsTo('Phonex\User', 'owner_id');
    }

    public function bcodes()
    {
        return $this->hasManyThrough('Phonex\BusinessCode', 'Phonex\BusinessCodesExport', 'group_id', 'export_id');
    }

//    public function bcodes()
//    {
//        return $this->hasMany('Phonex\BusinessCode', 'group_id');
//    }

    public function exports()
    {
        return $this->hasMany('Phonex\BusinessCode', 'group_id');
    }

    /* Helpers */
    public static function findByName($groupName)
    {
        return Group::where('name', $groupName)->first();
    }
}

app/Http/Controllers/GroupController.php
<?php namespace Phonex\Http\Controllers;

use Exception;
use Illuminate\Http\Exception\HttpResponseException;
use Phonex\Group;
use Phonex\Http\Requests;
use Phonex\Http\Requests\CreateGroupRequest;
use Phonex\Http\Requests\UpdateGroupRequest;
use Phonex\User;
use Redirect;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class GroupController extends Controller {

	public function __construct(){
	}

	public function index(){
		$groups = Group::paginate(15);
		return view('group.index', compact('groups'));
	}

    public function create()
    {
        return view('group.create');
    }

    public function store(CreateGroupRequest $request)
    {
        $group = new Group();
        $group->name = $request->get('name');

        if ($request->has('owner_username')){
            $owner = User::findByUsername($request->get('owner_username'));
            $group->owner_id = $owner->id;
        }

        $group->comment= $request->get('comment');
        $group->save();

        return Redirect::route('groups.index')
            ->with('success', 'New group ' . $group->name . ' has been created.');
    }

    public function show($id)
    {
        $group = Group::findOrFail($id);
        return view('group.show-details', compact('group'));
    }

    public function showUsers($id)
    {
        $group = Group::with('users')->findOrFail($id);
        return view('group.show-users', compact('group'));
    }

    public function showCodes($id)
    {
        $group = Group::with('exports')->findOrFail($id);
        return view('group.show-bcodes', compact('group'));
    }

    public function edit($id)
    {
        $group = Group::findOrFail($id);
        return view('group.edit', compact('group'));
    }

    public function update($id, UpdateGroupRequest $request)
    {
        $group = Group::findOrFail($id);
        $this->validate($request,
        [
            'name' => 'required|min:5|max:255|unique:groups,name,' . $group->id
        ]);

        $user = User::findByUsername($request->get('owner_username'));

        $group->name = $request->get('name');
        $group->comment = $request->get('comment');
        $group->owner_id = $user->id;
        $group->save();

        return Redirect::route('groups.show', [$group->id])
            ->with('success', 'Group has been updated.');
    }
}

resources/views/group/create.blade.php
@extends('content-with-header')

@section('title',"Create group")

@section('content')
    @parent

	<section class="content">

	<div class="row">
		<div class="col-sm-12">

            @include('errors.notifications')

            <div class="box box-default">
                <div class="box-header with-border">
                </div>

                <div class="box-body">
                    <form  role="form" method="POST" action="{{ route('groups.store') }}">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">

                        <h4>Group details</h4>

                        <div class="row">
                            <div class="col-md-4 ">
                                <div class="form-group"><label for="name" class="control-label">Name*</label>
                                    <input class="form-control" required value="{{ old('name') }}" placeholder="Enter group name" id="name" type="text" name="name">
                                </div>
                            </div>
                            <div class="col-md-4 ">
                                <div class="form-group"><label for="owner_username" class="control-label">Owner</label>
                                    <input class="form-control" value="{{ old('owner_username') }}" placeholder="Enter owner's username" id="owner_username" type="text" name="owner_username">
                                    {{--<span class="help-block">Owner of the group will be assigned as a support contact for newly created licenses (if not chosen otherwise during user creation).</span>--}}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4 ">
                                <div class="form-group">
                                    <label for="comment" class="control-label">Comment</label>
                                    <textarea name="comment" class="form-control" rows="3">{{ old('comment') }}</textarea>
                                </div>
                            </div>
                        </div>

                        <p>* Required fields</p>

                        <div class="row">
                            <div class="col-md-12">
                                <div><input class="btn-large btn-primary btn" type="submit" value="Submit"> <input class="btn-large btn-default btn" type="reset" value="Reset"></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
		</div>
	</div>


	</section>
@endsection

resources/views/group/edit.blade.php
@extends('form.form-create')
@section('title', 'Group #' . $group->id)
@section('subtitle', 'Edit')

@section('form-nav')
    <div class="row form-inline" style="margin-bottom: 5px">
        <div class="col-sm-6">
            <a class="btn btn-sm btn-primary view-btn-create" href="{{ route('groups.show', $group->id) }}">
                <i class="fa fa-angle-left"></i> Cancel editing
            </a>
        </div>

        <div class="col-sm-6 text-right">
        </div>
    </div>
@endsection

@section('form')
    {!! \Form::open(['method' => 'put', 'route' => array('groups.update', $group->id)]) !!}
    <input type="hidden" name="_token" value="{{ csrf_token() }}">

    <div class="row">
        <div class="col-md-2">
            <dl>
                <dt>Name</dt>
                <dd>
                    <input class="form-control" type="text" name="name" value="{{old('name', $group->name)}}" />
                </dd>
            </dl>
        </div>
        <div class="col-md-2 ">
            <dl>
                <dt>Owner (username)</dt>
                <dd>
                    <input class="form-control" type="text" name="owner_username" value="{{old('owner_username', $group->owner ? $group->owner->username : '' )}}" />
                </dd>
            </dl>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 ">
            <dl>
                <dt>Comment</dt>
                <dd>
                    <textarea cols="8" name="comment" class="form-control">{{old('comment', $group->comment)}}</textarea>
                </dd>
            </dl>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div><input class="btn-large btn-primary btn" type="submit" value="Update"></div>
        </div>
    </div>
    {!! \Form::close() !!}
@endsection

resources/views/group/index.blade.php
@extends('content-with-header')

@section('title', 'Groups')
@section('subtitle', 'Manage')

@section('content')
    @parent

    <section class="content">
        @include('errors.notifications')

        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Groups</h3>
                <div class="box-tools">
                    <a class="btn btn-sm btn-primary" href="{{ route('groups.create') }}">
                        <i class="fa fa-plus-circle"></i> New Group
                    </a>
                </div>
            </div>
            <div class="box-body">

                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Group name</th>
                        <th>Owner</th>
                        <th>Comment</th>
                        <th>Users count</th>
                        <th class="text-center">Options</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($groups as $group)
                        <tr>
                            <td>{{ $group->id }}</td>
                            {{--<td><a href="{{ \URL::route('users.index', [ 'user_group[]' => $group->id ]) }}">{{ $group->name or '' }}</a></td>--}}
                            <td><a href="{{ route('groups.show', $group->id) }}">{{ $group->name }}</a></td>
                            <td>
                                @if($group->owner)
                                    <a href="{{ route('users.show', [ $group->owner->id ]) }}">{{ $group->owner->username }}</a>
                                @endif
                            </td>
                            <td>{{ $group->comment }}</td>
                            <td>{{ $group->users()->count()  }}</td>
                            <td class="text-center">
                                <div class="btn-group  btn-group-xs">
                                    <a class="btn btn-info view-btn-edit" href="{{ route('groups.show', $group->id) }}" title="Details"><i class="fa fa-pencil-square-o"></i> Details</a>
                                    <a class="btn btn-info view-btn-edit" href="{{ route('groups.users', $group->id) }}" title="Users"><i class="fa fa-users"></i> Users</a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>

            <div class="box-footer clearfix">
                <div class="pull-left">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">
                        Total {{ $groups->total() }} entries</div>
                </div>

                <div class="pull-right">
                    {!! $groups->appends(Request::except('page'))->render() !!}
                </div>
            </div>
        </div>

    </section>
@endsection

resources/views/group/show-bcodes.blade.php
@extends('group.show')

@section('options')
    <div class="row form-inline" style="margin-bottom: 5px">
        <div class="col-sm-6">
            {{--<a href="{{ route('users.index', [ 'user_group[]' => $group->id ]) }}" class="btn btn-default">Show in users list</a>--}}
        </div>

        <div class="col-sm-6 text-right">
        </div>
    </div>
@endsection

@section('details')
    @include('bcode.chips.bcodes-table', ['bcodes' => $group->bcodes])
@endsection

resources/views/group/show-details.blade.php
@extends('group.show')

@section('options')
    <div class="row form-inline" style="margin-bottom: 5px">
        <div class="col-sm-6">
            <a href="{{ route('groups.edit', [$group->id]) }}" class="btn btn-primary">Edit</a>
        </div>

        <div class="col-sm-6 text-right">
        </div>
    </div>
@endsection

@section('details')
    <h4>Group details</h4>

    <div class="row">
        <div class="col-md-2 ">
            <dl>
                <dt>Name</dt>
                <dd>{{ $group->name}}</dd>
            </dl>
        </div>
        <div class="col-md-2 ">
            <dl>
                <dt>Created at</dt>
                <dd>{{ $group->created_at }}</dd>
            </dl>
        </div>
        <div class="col-md-2 ">
            <dl>
                <dt>Group owner</dt>
                <dd>
                    @if($group->owner)
                        <a href="{{ route('users.show', $group->owner->id) }}">{{ $group->owner->username or ''}}</a>
                    @endif

                </dd>
            </dl>
        </div>
    </div>

    {{--<div class="row">--}}
        {{--<div class="col-md-2">--}}

        {{--</div>--}}
    {{--</div>--}}

    <div class="row">
        <div class="col-md-2 ">
            <dl>
                <dt>Comment</dt>
                <dd>{{ $group->comment }}</dd>
            </dl>
        </div>

    </div>

@endsection

resources/views/group/show-users.blade.php
@extends('group.show')

@section('options')
    <div class="row form-inline" style="margin-bottom: 5px">
        <div class="col-sm-6">
            <a href="{{ route('users.index', [ 'user_group[]' => $group->id ]) }}" class="btn btn-default">Show in users list</a>
        </div>

        <div class="col-sm-6 text-right">
        </div>
    </div>
@endsection

@section('details')
    @include('user.chips.users-simple-table', ['users' => $group->users])
@endsection

resources/views/group/show.blade.php
@extends('content-with-header')

@section('title', 'Group: '. $group->name)

@section('content')
    @parent

	<section class="content">

	<div class="row">
		<div class="col-sm-12">

            @include('errors.notifications')

            @include('group.chips.top-nav')

            <div class="box box-default">
                <div class="box-header with-border">
                    @yield('options')
                </div>

                <div class="box-body">
                    @yield('details')
                </div>
            </div>
		</div>
	</div>


	</section>

@endsection