app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Non authenticated pages
use Phonex\Jobs\CreateUserWithSubscriber;
use Phonex\Jobs\IssueProductLicense;
use Phonex\Jobs\RefreshSubscribers;
use Phonex\Model\Product;
use Phonex\User;

Route::get('home', 'HomeController@index');
Route::get('/', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
    'trial' => 'AccountController',
    'account' => 'AccountController', //alias
]);

Route::get('login', 'Auth\AuthController@getLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

Route::resource('products', 'Api\ProductControllerLegacy', ['only' => ['show', 'index']]);
Route::controller('qa', 'QaController'); // qa tools
Route::get('api/support-notifications/batch', 'Api\SupportNotificationsController@getBatch');
Route::post('api/support-notifications/batch', 'Api\SupportNotificationsController@postBatch');
Route::get('api/support-notification/{user}/{notification}', 'Api\SupportNotificationsController@getNotificationForUser');

Route::any('api/version-check', 'Api\VersionCheckController@versionCheck');

// Authenticated API using client certs
Route::group(['prefix'=>'api/auth/', 'middleware'=>['auth.client_cert']], function(){
    Route::get('products/apple', 'Api\ProductController@getAppleProducts');
    Route::get('products/google', 'Api\ProductController@getGoogleProducts');

    Route::get('products/available', 'Api\ProductController@getAvailableProducts');
    Route::get('products/purchased', 'Api\ProductController@getPurchasedProducts');
    Route::get('products/list-from-licenses', 'Api\ProductController@getLicensesProducts'); // List arbitrary user's products by providing license ids
    Route::any('purchase/appstore/payment-verif', 'Api\PurchaseController@postApplePaymentVerification');
    Route::any('purchase/play/payment-verif', 'Api\PurchaseController@postAndroidPaymentVerification');
    Route::any('purchase/play/payments-verif', 'Api\PurchaseController@postAndroidPaymentsVerification');
});

// Authenticated pages using client credentials
Route::group(['middleware' => ['auth', 'acl']], function() {
    Route::get('/', 'HomeController@index');

    /* Users + details */
	Route::resource('users', 'UserController');
    Route::post('users/{user}/reset-trial-counter', ['as'=>'users.reset-trial-counter', 'uses'=>'UserController@resetTrialCounter']);
    Route::get('users/{user}/push-lic-update', ['as'=>'users.push-lic-update', 'uses'=>'UserController@pushLicUpdate']);
    Route::post('users/{user}/force-logout', ['as'=>'users.force-logout', 'uses'=>'UserController@forceLogout']);
    // CL
    Route::get('users/{user}/licenses', ['as' => 'users.licenses', 'uses' => 'UserController@showLicenses']);
    Route::get('users/{user}/cl', ['as' => 'users.cl', 'uses' => 'UserController@showCl']);
    Route::get('users/{user}/stats', ['as' => 'users.stats', 'uses' => 'UserController@showStats']);
    Route::get('users/{user}/reg-stats', ['as' => 'users.reg-stats', 'uses' => 'UserController@showRegStats']);
    Route::get('users/{user}/error-reports', ['as' => 'users.error-reports', 'uses' => 'UserController@showErrorReports']);

    // Contact lists + alternative via get
    Route::delete('users/{user}/cl', ['uses' => 'UserController@deleteContact']);
    Route::delete('users/{user}/cl/{contactUser}', ['uses' => 'UserController@deleteContact']);
    Route::get('users/{user}/cl/delete/{contactUser}', ['uses' => 'UserController@deleteContact']);

    Route::get('users/{users}/new-license', ['as' => 'users.new-license', 'uses' => 'UserController@getNewLicense']);
    Route::post('users/{users}/new-license', ['as' => 'users.new-license', 'uses' => 'UserController@postNewLicense']);
    Route::patch('users/{users}/change-password', ['as' => 'users.change_password', 'uses' => 'UserController@changePassword']);
    Route::patch('users/{users}/add-user-to-cl', ['as' => 'users.add_user_to_cl', 'uses' => 'UserController@addUserToCl']);

    /* Group */
    Route::resource('groups', 'GroupController');
    Route::get('groups/{user}/users', ['as' => 'groups.users', 'uses' => 'GroupController@showUsers']);
    Route::get('groups/{user}/bcodes', ['as' => 'groups.bcodes', 'uses' => 'GroupController@showCodes']);

    /* Licenses */
    Route::resource('licenses', 'LicenseController', ['only' => ['index', 'edit', 'update', 'destroy']]);
    Route::get('licenses/delete/{id}', ['as'=>'licenses.delete', 'uses' => 'LicenseController@destroy']);

    /* Business Codes */
    Route::controller('bcodes', 'BusinessCodeController');

    /* Statistics */
    Route::controller('stats', 'StatsController');

    /* Reports */
    Route::get('reports/last-errors', 'ReportsController@lastErrors');
    Route::get('reports/last-trial-requests', 'ReportsController@lastTrialRequests');
    Route::post('reports/reset-trial-counter', 'ReportsController@resetTrialCounter');

    /* Admin only pages */
    Route::get('logs', ['acl-resource' => 'logs',
        'uses' => '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index'
    ]);
    Route::any('adminer', ['acl-resource' => 'adminer',
        'uses' => '\Miroc\LaravelAdminer\AdminerController@index']);
});

app/LicenseType.php
<?php namespace Phonex;

use Illuminate\Database\Eloquent\Model;

/**
 * @property mixed days
 * @property mixed id
 */
class LicenseType extends Model{
    const EXPIRATION_DAY = "day";
    const EXPIRATION_WEEK = "week";
    const EXPIRATION_MONTH = "month";
    const EXPIRATION_QUARTER = "quarter";
    const EXPIRATION_HALF_YEAR = "half_year";
    const EXPIRATION_YEAR = "year";
    const EXPIRATION_INFINITE = "infinite";
    const EXPIRATION_CONSUMABLE = "consumable";

    protected $table = "license_types";
    
    public function licenses(){
        return $this->hasMany('Phonex\License', 'license_type_id');
    }

    /* Helpers */
    public function readableType(){
        return ucfirst($this->name) . " (" .  $this->days . " days )";
    }

    public static function getWeek(){
        return self::findByName(self::EXPIRATION_WEEK);
    }
    public static function getDay(){
        return self::findByName(self::EXPIRATION_DAY);
    }
    public static function getMonth(){
        return self::findByName(self::EXPIRATION_MONTH);
    }
    public static function getQuarterOfYear(){
        return self::findByName(self::EXPIRATION_QUARTER);
    }
    public static function getHalfYear(){
        return self::findByName(self::EXPIRATION_HALF_YEAR);
    }
    public static function getYear(){
        return self::findByName(self::EXPIRATION_YEAR);
    }
    public static function getInfinite(){
        return self::findByName(self::EXPIRATION_INFINITE);
    }

    public static function findByName($name){
        return LicenseType::where('name', $name)->first();
    }

    /* Accessors */
    //uc_name_with_days
    public function getUcNameWithDaysAttribute()
    {
        return ucfirst($this->name) . " (" . $this->days . " days)";
    }

    public function getUcNameAttribute()
    {
        return ucfirst($this->name);
    }


}

resources/views/bcode/create_pair.blade.php
@extends('form.form-create')
@section('title', "New code pairs export")
@section('form')
    <form  role="form" method="POST" action="/bcodes/generate-code-pairs">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">

        <h4>Code pair</h4>
        <p>Specify number of pairs you want to generate and license details. After both codes are used, newly created users are automatically connected via their contact lists.</p>

        <?php $numberDesc  = 'Number of pairs'; ?>
        @include('bcode.chips.new-codes-form', compact('groups', 'licenseTypes', 'licenseFuncTypes', 'numberDesc'))

    </form>
@endsection

resources/views/bcode/create_single_codes.blade.php
@extends('form.form-create')
@section('title', "New single codes export")
@section('form')
    <form  role="form" method="POST" action="/bcodes/generate-single-codes">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">

        <h4>Single codes</h4>
        {{--<p></p>--}}

        @include('bcode.chips.new-codes-form', compact('groups', 'licenseTypes', 'licenseFuncTypes'))

    </form>
@endsection

resources/views/bcode/export-details.blade.php
@extends('content-with-header')

@section('title', 'Export: #'. $export->id)
{{--@section('subtitle', 'Manage')--}}

@section('content')
    @parent

    <section class="content">

        <div class="row">
            <div class="col-sm-12">

                @include('errors.notifications')

                <div class="box box-default">
                    <div class="box-header with-border">

                        {{--<div class="row form-inline" style="margin-bottom: 5px">--}}
                            {{--<div class="col-sm-6">--}}
                                {{--<a href="{{ \URL::route('users.edit', [$user->id]) }}" class="btn btn-primary">Edit</a>--}}
                            {{--</div>--}}

                            {{--<div class="col-sm-6 text-right">--}}
                            {{--</div>--}}
                        {{--</div>--}}
                    </div>

                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-2 ">
                                <dl>
                                    <dt>Created at</dt>
                                    <dd>{{ $export->created_at }}</dd>
                                </dl>
                            </div>
                            <div class="col-md-2 ">
                                <dl>
                                    <dt>Created by</dt>
                                    <dd>@if($export->creator)<a href="{{ route('users.show', [$export->creator->id]) }}">{{ $export->creator->username }}</a>@endif</dd>
                                </dl>
                            </div>
                            <div class="col-md-2 ">
                                <dl>
                                    <dt>Exported to mail</dt>
                                    <dd>{{ $export->email }}</dd>
                                </dl>
                            </div>
                        </div>

                        @if($firstCode)
                        <div class="row">
                            <div class="col-md-2 ">
                                <dl>
                                    <dt>Product</dt>
                                    <dd>{{$export->product->uc_name}}</dd>
                                </dl>
                            </div>
                            {{--<div class="col-md-2 ">--}}
                                {{--<dl>--}}
                                    {{--<dt>Type</dt>--}}
                                    {{--<dd>--}}
                                        {{--@if($export->licenseFuncType)--}}
                                            {{--{{$export->licenseFuncType->uc_name}}--}}
                                        {{--@else--}}
                                            {{--{{ $firstCode->licenseFuncType->uc_name }}--}}
                                        {{--@endif--}}
                                    {{--</dd>--}}
                                {{--</dl>--}}
                            {{--</div>--}}
                            {{--<div class="col-md-2 ">--}}
                                {{--<dl>--}}
                                    {{--<dt>Expiration</dt>--}}
                                    {{--<dd>--}}
                                        {{--@if($export->LicenseType)--}}
                                            {{--{{$export->LicenseType->uc_name}}--}}
                                        {{--@else--}}
                                            {{--{{ $firstCode->licenseType->uc_name_with_days }}--}}
                                        {{--@endif--}}

                                    {{--</dd>--}}
                                {{--</dl>--}}
                            {{--</div>--}}
                            <div class="col-md-2 ">
                                <dl>
                                    <dt>Group</dt>
                                    <dd>
                                        @if($export->group)
                                            <a href="{{route('groups.show', $export->group->id)}}">{{$export->group->name}}</a>
                                        @elseif($firstCode->group)
                                            <a href="{{route('groups.show', $firstCode->group->id)}}">{{$firstCode->group->name}}</a>
                                        @else
                                            -
                                        @endif
                                    </dd>
                                </dl>
                            </div>
                            <div class="col-md-2 ">
                                <dl>
                                    <dt>Parent user</dt>
                                    <dd>
                                        @if($export->parent)
                                            <a href="{{ route('users.show', [$export->parent->id]) }}">{{ $export->parent->username }}</a>
                                        @elseif($firstCode->parent)
                                            <a href="{{ route('users.show', [$firstCode->parent->id]) }}">{{ $firstCode->parent->username }}</a>
                                        @else
                                            -
                                        @endif
                                    </dd>
                                </dl>
                            </div>
                        </div>
                        @endif

                        <div class="row">
                            <div class="col-md-2 ">
                                <dl>
                                    <dt>Comment</dt>
                                    <dd>{{ $export->comment }}</dd>
                                </dl>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                @if(isset($codePairs))
                                    @include('bcode.chips.code-pairs-table', compact('codePairs'))
                                @elseif(isset($codes))
                                    @include('bcode.chips.single-codes-table', compact('codes'))
                                @endif
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>


    </section>

@endsection

resources/views/bcode/exports.blade.php
@extends('content-with-header')

@section('title', 'Business codes')
@section('subtitle', 'Exports')

@section('content')
    @parent

    <section class="content">
        @include('errors.notifications')

        <div class="box">
            <div class="box-header">
                <h3 class="box-title">List of exports</h3>
                <div class="box-tools">
                </div>
            </div>
            <div class="box-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Type</th>
                            <th>Creator</th>
                            <th>Created at</th>
                            <th>Exported to email</th>
                            <th>Group</th>
                            <th>Codes count</th>
                            <th class="text-center">Options</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($items as $item)
                        <tr>
                            <td>{{ $item->id }}</td>
                            <td>{{ $item->type }}</td>
                            <td>@if($item->creator)<a href="{{ route('users.show', $item->creator->id) }}">{{ $item->creator->username }}@endif</a></td>
                            <td>{{ $item->created_at }}</td>
                            <td>{{ $item->email }}</td>
                            <td>@if($item->group) <a href="{{route('groups.show', $item->group->id)}}">{{$item->group->name}}</a>@endif</td>
                            <td>{{ $item->codes->count() }}</td>
                            <td class="text-center">
                                <div class="btn-group  btn-group-xs">
                                    <a type="button" class="btn btn-info view-btn-edit" href="{{ "/bcodes/export/" . $item->id }}" title="Edit"><i class="fa fa-pencil-square-o"></i> Details</a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            {{--<div class="box-footer clearfix">--}}
                {{--<div class="pull-left">--}}
                    {{--<div class="dataTables_info" id="example2_info" role="status" aria-live="polite">--}}
                        {{--Total {{ $bcodes->total() }} entries</div>--}}
                {{--</div>--}}

                {{--<div class="pull-right">--}}
                    {{--{!! $bcodes->appends(Request::except('page'))->render(); !!}--}}
                {{--</div>--}}
            {{--</div>--}}
        </div>

    </section>
@endsection

resources/views/bcode/index.blade.php
@extends('content-with-header')

@section('title', 'Business codes')
@section('subtitle', 'Manage')

@section('content')
    @parent

    <section class="content">
        @include('errors.notifications')

        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Business codes</h3>
                <div class="box-tools">
                    {{--<a class="btn btn-sm btn-primary view-btn-create" href="/bcodes/generate-single-codes/">--}}
                        {{--<i class="fa fa-plus-circle"></i> New single codes--}}
                    {{--</a>--}}

                    <form class="form-inline inline-block" action="/bcodes" method="get">

                        <div class="input-group">
                            <input type="text" name="code" value="{{Request::get('code')}}" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search by code">
                            <div class="input-group-btn">
                                <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </form>

                    <a class="btn btn-sm btn-primary view-btn-create" href="/bcodes/generate-code-pairs/">
                        <i class="fa fa-plus-circle"></i> New code pairs
                    </a>
                </div>
            </div>
            <div class="box-body">
                @include('bcode.chips.bcodes-table')
            </div>
            <div class="box-footer clearfix">
                <div class="pull-left">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">
                        Total {{ $bcodes->total() }} entries</div>
                </div>

                <div class="pull-right">
                    {!! $bcodes->appends(Request::except('page'))->render() !!}
                </div>
            </div>
        </div>

    </section>
@endsection